name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  linux-build:
    name: linux-build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: Checkout raylib repo
      uses: actions/checkout@v4
      with:
        repository: raysan5/raylib
        path: raylib
    
    - name: Setup Environment
      run: | 
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libwayland-dev libxkbcommon-dev cmake make gcc
        mkdir release
        ls
      shell: bash
        
    - name: Build raylib Library
      run: |
        cd raylib/src
        gcc --version
        make PLATFORM=PLATFORM_DESKTOP

    - name: Build Product
      run: |
        gcc main.c -o puffersbubbleblast_linux.out -O1 -Wall -std=c99 -Wno-missing-braces -I ./raylib/src -L ./raylib/src -lraylib -lGL -lm -lpthread -ldl -lrt -lX11

    - name: Generate Artifacts
      run: |
        ls
        cp puffersbubbleblast_linux.out release
        cp -r assets release
        cp README.md release
        cp LICENSE release
        ls release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: puffersbubbleblast_linux
        path: release

  windows-build:
    name: Build for Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: Checkout raylib repo
      uses: actions/checkout@v4
      with:
        repository: raysan5/raylib
        path: raylib
    
    - name: Setup Environment
      run: |
        choco install mingw -y
        setx PATH "%PATH%;C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"
        mkdir bin
      shell: cmd
        
    - name: Build raylib Library
      run: |
        cd raylib/src
        mingw32-make PLATFORM=PLATFORM_DESKTOP

    - name: Build Product
      run: |
        gcc main.c -o puffersbubbleblast_windows.exe -O1 -Wall -std=c99 -Wno-missing-braces -I ./raylib/src -L ./raylib/src -lraylib -lopengl32 -lgdi32 -lwinmm

    - name: Generate Artifacts
      run: |
        dir
        mkdir release
        copy puffersbubbleblast_windows.exe release
        xcopy assets release\assets /E /I
        copy README.md release
        copy LICENSE release
        dir release
      shell: cmd

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: puffersbubbleblast_windows
        path: release